using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PlanScoreCard.Models
{
    public class StructureModel
    {
        public string StructureId { get; set; }
        public string StructureCode { get; set; }
        public bool AutoGenerated { get; set; }
        public string StructureComment { get; set; }
    }
}
